# Generated by Django 5.2.7 on 2025-10-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("user_transcript", models.TextField(blank=True, default="")),
                ("ai_transcript", models.TextField(blank=True, default="")),
                ("summary", models.TextField(blank=True, default="")),
                ("satisfaction_score", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
