# Generated by Django 5.2.7 on 2025-10-28 04:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_activity",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "session_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("user_name", models.CharField(blank=True, default="", max_length=128)),
                ("conversation", models.TextField(blank=True, default="")),
                ("summary", models.TextField(blank=True, default="")),
                ("satisfaction_rating", models.IntegerField(blank=True, null=True)),
                (
                    "satisfaction_label",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("user_behavior", models.TextField(blank=True, default="")),
                (
                    "conversation_topic",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("feedback_summary", models.TextField(blank=True, default="")),
                ("analysis_timestamp", models.DateTimeField(blank=True, null=True)),
                ("raw_json", models.JSONField(blank=True, null=True)),
                ("raw_response", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "voice_conversation",
                "ordering": ["-last_activity", "-id"],
                "indexes": [
                    models.Index(
                        fields=["session_id"], name="voice_conve_session_434874_idx"
                    ),
                    models.Index(
                        fields=["user_name"], name="voice_conve_user_na_57324b_idx"
                    ),
                    models.Index(
                        fields=["last_activity"], name="voice_conve_last_ac_f791eb_idx"
                    ),
                ],
            },
        ),
    ]
