# Generated by Django 5.2.7 on 2025-10-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="satisfaction_label",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
