# Generated by Django 5.2.7 on 2025-10-21 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice", "0001_squashed_single_table"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="conversation",
            new_name="voice_conve_session_434874_idx",
            old_name="voice_conve_session_idx",
        ),
        migrations.RenameIndex(
            model_name="conversation",
            new_name="voice_conve_last_ac_f791eb_idx",
            old_name="voice_conve_last_act_idx",
        ),
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="last_activity",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
