# Generated by Django 5.2.7 on 2025-10-14 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice", "0002_conversation_satisfaction_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="conversation",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="conversation",
            name="structured",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="BehaviorAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField()),
                ("model", models.CharField(default="gpt-4o-mini", max_length=64)),
                ("raw", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="voice.conversation",
                    ),
                ),
            ],
        ),
    ]
