# Generated by Django 5.2.7 on 2025-10-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "voice",
            "0002_rename_voice_conve_session_idx_voice_conve_session_434874_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversation_id",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("summary", models.TextField(blank=True, default="")),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
