# Generated by Django 5.2.7 on 2025-10-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice", "0003_conversation_conversation_conversation_structured_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="satisfaction_label",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="satisfaction_score",
        ),
        migrations.AddField(
            model_name="conversation",
            name="satisfaction_indicator",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
