# Generated by Django 5.2.7 on 2025-10-15 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voice", "0004_remove_conversation_satisfaction_label_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BehaviorAnalysis",
        ),
    ]
