# Generated by Django 5.2.7 on 2025-10-15 05:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice", "0005_delete_behavioranalysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="autosave_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="conversation",
            name="ended_reason",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="conversation",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conversation",
            name="last_activity",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="conversation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
