# Generated by Django 5.2.7 on 2025-10-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice", "0006_conversation_autosave_count_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ["-last_activity", "-id"]},
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="ai_transcript",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="autosave_count",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="ended_reason",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="is_closed",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="user_transcript",
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["session_id"], name="voice_conve_session_434874_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["-last_activity"], name="voice_conve_last_ac_55c037_idx"
            ),
        ),
    ]
