# Generated by Django 5.2.7 on 2025-10-17 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voice", "0007_alter_conversation_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="satisfaction_indicator",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="structured",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="summary",
        ),
    ]
