# Generated by Django 5.2.7 on 2025-10-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice", "0008_remove_conversation_satisfaction_indicator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="satisfaction_indicator",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="conversation",
            name="structured",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
    ]
